export const metadata = {
  title: "Admin Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Layout do Admin</h1>
        {children}
      </body>
    </html>
  );
}
